### ISSUE TITLE
tk2tablelist() returns Tcl/Tk error

### ISSUE THREAD

**Issue by GegznaV** [SciViews/tcltk2#4]
The example from package **tcltk2** (see code below) returns the following error:

![image](https://user-images.githubusercontent.com/12725868/77835702-f8e3e600-7157-11ea-858f-4f5f684a5b92.png)

**Please, fix the functionality of function `tk2tablelist()`.**

The example:

```r
library(tcltk2)

## A tablelist example
tt <- tktoplevel()
tlist <- tk2tablelist(tt, columntitles = c("First column", "Second column"),
    stretch = "all", expand = 1)
tkpack(tlist, fill = "both")
tkinsert(tlist, "end", c("first row", "another value"))
tkinsert(tlist, "end", c("another row", "bla bla"))
tbut <- tk2button(tt, text = "Done", command = function () tkdestroy(tt))
tkpack(tbut)
```

**Comment by phgrosjean** [comment]
Tested the level version on macOS Big Sur => it works without error.
