### ISSUE TITLE
Update Tcl/Tk library "Tablelist"

### ISSUE THREAD

**Issue by GegznaV** [SciViews/tcltk2#5]
Currently, **tcltk2** uses "Tablelist" v5.5. Please, update it to v6.8 (or even more recent version): https://www.nemethi.de/
The problem is that even though I add v6.8 to Tcl/Tk path, version v5.5 is used as it is added though **tcltk2**.

**Comment by phgrosjean** [comment]
Done in latest development version (Tablelist 6.9).
